version: '3.8'
services:
  xve:
    build:
      context: .
      dockerfile: Dockerfile
    image: xve-wsl:latest
    container_name: xve-container
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "81:81"
      - "8443:8443"

  # ... your existing nginx-proxy-manager services here ...
