version: '3.8'
services:
  nginx-proxy-manager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:80'   # Changed from 80 to 8080 to avoid conflict with Laravel Sail
      - '81:81'     # Admin interface - no conflict
      - '8443:443'  # Changed from 443 to 8443 to avoid conflict with Laravel Sail
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Europe/Brussels
    networks:
      - npm_network

networks:
  npm_network:
    external: false